### ISSUE TITLE
Error when starting BPMEventEmitter

### ISSUE THREAD

**Issue by goveebee** [ibmbpm/bpm_analytics#4]
When I try to start the BPMEventEmitter application, I get this error.
Googling and the supplied pdf say that I need to update BPMEventEmitter.yml with the correct host of elasticsearch in the files for ALL instances of the BPM servers. It also says that I need to change the class loader order of the WAR module to Classes loaded with local class loader first (parent last), which I've done. Still get this error. My BPM-server has connection to the Elastic-server. Please help.

`[2017-12-05 09:56:30:861 CET] 00000178 LifeCycleMana E class com.ibm.bpm.mon.oi.LifeCycleManageBean startMethod CWMCD1016E: The creation of the Elasticsearch index mapping failed on an exception.
                                 org.elasticsearch.client.ResponseException: PUT http://192.168.1.174:9200/bpm-events/_mapping/ProcessEvent: HTTP/1.1 400 Bad Request
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Could not convert [mon:id.index] to boolean"}],"type":"illegal_argument_exception","reason":"Could not convert [mon:id.index] to boolean","caused_by":{"type":"illegal_argument_exception","reason":"Failed to parse value [no] as only [true] or [false] are allowed."}},"status":400}`

**Comment by sundag** [comment]
Hi @goveebee
    What's the Elasticsearch version you are using? Are you using ES 6? There is a big change for index field on elastic search 6. It's accept true/false only on 6. 
https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-index.html
But accept analyzed/not_analyzed/no on ES 5.x release.
    We don't support ES6 now. The verified versions for ES is listed in readme as below:

Elasticsearch & Kibana

    Version 5.1.x
    Version 5.4.x
    Version 5.5.x

**Comment by goveebee** [comment]
Yes, I'm using ES6. I better downgrade my version then. Any idea of when ES6 will be supported?

Thank you for your quick respons. :)
