### ISSUE TITLE
Issue starting EventSummaryAgent

### ISSUE THREAD

**Issue by pmisra19** [ibmbpm/bpm_analytics#7]
Having issue starting  Event summary agent. 
E:\EventSummaryAgent\bin>EventSummaryAgent.bat
IBM BPM Event Summary Agent
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

Able to setup the rest of the parts from the bpm end and kibana/elastic.
BPM version is 8.6.201712
Kibana\Elastic version is 5.5.3

Was able to run a a early release of the event summary agent but the one with the lastest download is causing issues.  Please advice

**Comment by zhangs-ibm** [comment]
@pmisra19, I guess your java full path include a blank space, please open the EventSummaryAgent.bat and make the following changes:
```
%JAVA_EXE% %LOGGING_PROPS% %HEAP_PROPS% -cp %DIR%\lib\* com.ibm.bpm.mon.oi.combine.EventSummaryAgent %*
```
==>
```
"%JAVA_EXE%" %LOGGING_PROPS% %HEAP_PROPS% -cp %DIR%\lib\* com.ibm.bpm.mon.oi.combine.EventSummaryAgent %*
```

**Comment by pmisra19** [comment]
thanks Joshua
